require:
  - standard/cop/block_single_line_braces
  - rubocop-md

AllCops:
  Exclude:
    - 'bin/*'
    - 'tmp/**/*'
    - 'Gemfile'
    - 'vendor/**/*'
    - 'gemfiles/**/*'
    - 'benchmarks/**/*'
  DisplayCopNames: true
  SuggestExtensions: false
  NewCops: disable
  TargetRubyVersion: 2.7

inherit_gem:
  standard: config/base.yml

Standard/BlockSingleLineBraces:
  Enabled: false

Layout/InitialIndentation:
  Enabled: false
